# Generated by Django 5.1.1 on 2024-09-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('rider', 'Rider'), ('admin', 'Admin')], default='rider', max_length=10),
        ),
    ]
